Algoritmo "ESTRUTURAS_SEQUENCIAIS03"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2022
Var
// Seção de Declarações das variáveis 
   x, y : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 100
   y <- 100
   enquanto x <> y faca
      escreva("Olha")
      x <- RaizQ(y)
   fimenquanto

Fimalgoritmo