Algoritmo "ESTRUTURAS_REPETITIVAS02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2022
Var
// Seção de Declarações das variáveis 
 x, y : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 x <- 1
 y <- 0
 enquanto x <= 10 faca
  escreval(x)
  x <- x + 1
  y <- y +10
 fimenquanto

Fimalgoritmo