Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2022
Var
// Seção de Declarações das variáveis 
   a, b, potencia : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval(" Digite o numero: ")
   leia(a)
   escreval(" Digite a potencia: ")
   leia(b)
   potencia <- a^b
   escreval(a, " ELEVADO A", b, "º Potencia = ", potencia)


Fimalgoritmo