Algoritmo "RAIO"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2022
Var
// Seção de Declarações das variáveis 
   area, raio : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   EscrevaL ("Digite o Valor do RAIO: ")
   leia (raio)
   area <- Pi * raio ^ (2)
   escreva("A area é ",area:8:3)
   

Fimalgoritmo