Algoritmo "SOMAR"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2022
Var
// Seção de Declarações das variáveis
   n1, n2, rest : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite um numero: ")
   Leia(n1)
   EscrevaL("+")
   Escreva("Digite o outro numero: ")
   Leia(n2)

   rest <- (n1 + n2)
   escreva("RESULTADO = ", rest)

Fimalgoritmo