Algoritmo "test_enquanto"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2022
Var
// Seção de Declarações das variáveis 
   x, soma : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escrevaL("Digite o Primeiro Numero: ")
   leia(x)

   soma <- 0
   enquanto x <> 0 faca
      soma <- soma + x
      escrevaL("digite outro numero ")
      leia(x)
   fimenquanto
   escreval("SOMA = ", soma)

Fimalgoritmo