Algoritmo "test_condicional001"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2022
Var
   // Seção de Declarações das variáveis
   hora : inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Programa que te deseja algo bom...")
   escreval("Digite quantas horas são: ")
   leia(hora)

      se hora <= 12 entao
         escreval("BoomDia")
      fimse
  

Fimalgoritmo