a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços ? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É Alphanumerico?', a.isalpha())
print('Está em Maiúsculas? ', a.isupper())
print('Está em Minúsculas? ', a.islower())
print(f'O que você digitou foi: {a}')
